[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Beno√Æt Zugmeyer <bzugmeyer@gmail.com>"]
edition = "2021"

[dependencies]
native-tls = "0.2.3"
bytecount = "0.6.0"
lazy_static = "1.4.0"
itertools = "0.14.0"
