[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["Beno√Æt Zugmeyer <bzugmeyer@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.7.11"
regex = "1.1.0"
rayon = "1.0.3"
lazy_static = "1.2.0"
