[package]
authors = ["Beno√Æt Zugmeyer <bzugmeyer@gmail.com>"]
name = "advent_of_code_2016"
version = "0.1.0"
edition = "2018"

[dependencies]
itertools = "0.5.6"
regex = "0.1.80"
rust-crypto = "0.2.36"
permutohedron = "0.2.2"

[dependencies.nom]
version = "2.0.1"
features = ["verbose-errors"]
